customxxx: zzzssss
pull_request_title: Custom PR title<a>1</a>
pull_request_labels:
  - crowdin<a>1</a>
  - l10n
commit_message: 'Fix: New translations %original_file_name% from Crowdin<a>1</a>'
append_commit_message: 
export_languages:
  - uk<a>1</a>
  - ja
pull_request_assignees:
  - login1<a>1</a>
  - login2
pull_request_reviewers:
  - login1<a>1</a>
  - login2
files:
  - source: /1_multilingual.csv
    translation: /%two_letters_code%/multilingual_tr.csv
    multilingual: <a>1</a>
    first_line_contains_header: <a>1</a>
    scheme: 'identifier,source_phrase,translation,<h1>zzz</h1>'
  - source: /1_android.xml
    translation: /%two_letters_code%/%original_file_name%
    labels:
      - android
      - <a>1</a>
    translation_replace:
      _en: ''
    ignore:
      - /test/file.properties
      - /example.properties
    excluded_target_languages:
      - uk
      - fr
    type: <a>1</a>
    update_option: <a>1</a>
    custom_segmentation: /rules/<a>1</a>.srx.xml
    translate_attributes: 1
    translate_content: 0
    content_segmentation: 1
    escape_quotes: '1,'
    escape_special_characters: 0
