customxxx: zzzssss
pull_request_title: Custom PR title<a>1</a>
pull_request_labels:
  - crowdin<a>1</a>
  - l10n
commit_message: 'Fix: New translations %original_file_name% from Crowdin<a>1</a>'
append_commit_message: 
export_languages:
  - uk<a>1</a>
  - ja
pull_request_assignees:
  - login1<a>1</a>
  - login2
pull_request_reviewers:
  - login1<a>1</a>
  - login2
files:
  - source: /README.md
    translation: /README-%two_letters_code%.md
