files:
  - source: /1_multilingual.csv #zghfhgfhf
    translation: /%two_letters_code%/multilingual_tr.csv
    multilingual: <a>1</a>
    first_line_contains_header: <a>1</a>
    scheme: 'identifier,source_phrase,translation,<h1>zzz</h1>'
    zzz: 'iq1q1q1'
  - source: /1_android.xml
    translation: /%two_letters_code%/%original_file_name%
    "labels" : [
      "android",
      "<a>1</a>"
    ]
    "translation_replace": {
      "_en": ""
    }
